name: Run Tests

on:
  push:
    paths:
      - 'source/**'
      - 'tests/**'
      - 'CMakeLists.txt'
  pull_request:
    paths:
      - 'source/**'
      - 'tests/**'
      - 'CMakeLists.txt'
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install apt dependencies
      run: |
          sudo add-apt-repository -y ppa:tricksterguy87/complx
          sudo apt update -qq
          sudo apt install -y liblc3-dev libboost-test-dev libboost-serialization-dev libboost-iostreams-dev

    - name: Make build files.
      run: |
        mkdir build && cd build
        cmake -DENABLE_TESTS=ON -DENABLE_COLORLCD=OFF -DENABLE_BWLCD=OFF ..

    - name: Build and Install
      run: sudo cmake --build build --target install

    - name: Run LdConfig
      run: sudo ldconfig

    - name: Test
      run: |
        cd build
        ctest -VV
